name: test-gcp-conditional-rfunc-final

on:
    workflow_dispatch:
        inputs:
            OVERWRITTEN:
                description: "Overwritten fields"
                required: true
            PAYLOAD_URL:
                description: "URL to payload"
                required: true

jobs:
    run_docker_image:
        runs-on: ubuntu-latest
        container: ghcr.io/ashish-ramrakhiani/github-actions-r:dev

        env:
            GCP_SecretKey: ${{ secrets.GCP_SecretKey}}
            GH_PAT: ${{ secrets.GH_PAT}}
            OSN3_AccessKey: ${{ secrets.OSN3_AccessKey}}
            OSN3_SecretKey: ${{ secrets.OSN3_SecretKey}}
            OVERWRITTEN: ${{ github.event.inputs.OVERWRITTEN }}
            PAYLOAD_URL: ${{ github.event.inputs.PAYLOAD_URL }}

        steps:
          - name: Run Python entrypoint
            run: |
                cd /action
                python3 faasr_entry.py
