name: test-gcp-conditional-rfunc
on:
  workflow_dispatch:
    inputs:
      OVERWRITTEN:
        description: Overwritten fields
        required: false
        default: '{}'
      PAYLOAD_URL:
        description: URL to payload
        required: false
        default: Ashish-Ramrakhiani/FaaSr-workflow-public/main/rworkflow.json
  schedule:
  - cron: '*/5 * * * *'
jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    container: ghcr.io/ashish-ramrakhiani/github-actions-r:2.0
    env:
      GCP_SecretKey: ${{ secrets.GCP_SecretKey}}
      GH_PAT: ${{ secrets.GH_PAT}}
      My_S3_Bucket_AccessKey: ${{ secrets.My_S3_Bucket_AccessKey}}
      My_S3_Bucket_SecretKey: ${{ secrets.My_S3_Bucket_SecretKey}}
      OVERWRITTEN: ${{ github.event.inputs.OVERWRITTEN || '{}' }}
      PAYLOAD_URL: ${{ github.event.inputs.PAYLOAD_URL || 'Ashish-Ramrakhiani/FaaSr-workflow-public/main/rworkflow.json' }}
    steps:
    - name: Run Python entrypoint
      run: 'cd /action

        python3 faasr_entry.py

        '
